CREATE TABLE IF NOT EXISTS agents (
    agent_id TEXT PRIMARY KEY,
    agent_name TEXT NOT NULL,
    joined_on TEXT NOT NULL,
    inactive_on TEXT,
    initial_contract_type TEXT NOT NULL CHECK (initial_contract_type IN ('salary', 'commission')),
    CHECK (inactive_on IS NULL OR inactive_on >= joined_on)
);

CREATE TABLE IF NOT EXISTS kpi_rules (
    rule_id TEXT PRIMARY KEY,
    valid_from_month TEXT NOT NULL,
    valid_to_month TEXT,
    premium_threshold_satang BIGINT NOT NULL CHECK (premium_threshold_satang >= 0),
    policy_threshold INTEGER NOT NULL CHECK (policy_threshold >= 0),
    required_streak INTEGER NOT NULL CHECK (required_streak > 0),
    comparison_operator TEXT NOT NULL CHECK (comparison_operator = '>'),
    UNIQUE (valid_from_month, valid_to_month)
);

CREATE TABLE IF NOT EXISTS monthly_agent_performance (
    performance_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id TEXT NOT NULL REFERENCES agents(agent_id),
    month_start TEXT NOT NULL,
    total_premium_satang BIGINT,
    new_policy_count INTEGER,
    data_status TEXT NOT NULL CHECK (data_status IN ('COMPLETE', 'PENDING')),
    source_kind TEXT NOT NULL CHECK (source_kind IN ('synthetic', 'external')),
    month_closed INTEGER NOT NULL DEFAULT 1 CHECK (month_closed IN (0, 1)),
    input_revision INTEGER NOT NULL DEFAULT 1 CHECK (input_revision > 0),
    input_hash TEXT NOT NULL,
    UNIQUE (agent_id, month_start)
);

CREATE TABLE IF NOT EXISTS monthly_kpi_evaluations (
    evaluation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    performance_id BIGINT NOT NULL REFERENCES monthly_agent_performance(performance_id),
    rule_id TEXT REFERENCES kpi_rules(rule_id),
    evaluation_revision INTEGER NOT NULL CHECK (evaluation_revision > 0),
    result TEXT NOT NULL CHECK (result IN ('PASS', 'FAIL', 'PENDING')),
    pass_streak INTEGER NOT NULL CHECK (pass_streak >= 0),
    fail_streak INTEGER NOT NULL CHECK (fail_streak >= 0),
    evaluated_at TEXT NOT NULL,
    input_hash TEXT NOT NULL,
    performance_input_revision INTEGER NOT NULL,
    snapshot_total_premium_satang BIGINT,
    snapshot_new_policy_count INTEGER,
    snapshot_data_status TEXT NOT NULL CHECK (snapshot_data_status IN ('COMPLETE', 'PENDING')),
    snapshot_rule_premium_threshold_satang BIGINT NOT NULL,
    snapshot_rule_policy_threshold INTEGER NOT NULL,
    snapshot_rule_required_streak INTEGER NOT NULL,
    snapshot_rule_comparison_operator TEXT NOT NULL CHECK (snapshot_rule_comparison_operator = '>'),
    is_current INTEGER NOT NULL DEFAULT 1 CHECK (is_current IN (0, 1)),
    UNIQUE (performance_id, evaluation_revision)
);

CREATE UNIQUE INDEX IF NOT EXISTS one_current_evaluation_performance
ON monthly_kpi_evaluations(performance_id)
WHERE is_current = 1;

CREATE TABLE IF NOT EXISTS contract_history (
    contract_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id TEXT NOT NULL REFERENCES agents(agent_id),
    from_type TEXT CHECK (from_type IS NULL OR from_type IN ('salary', 'commission')),
    to_type TEXT NOT NULL CHECK (to_type IN ('salary', 'commission')),
    effective_from TEXT NOT NULL,
    trigger_evaluation_id BIGINT REFERENCES monthly_kpi_evaluations(evaluation_id),
    reason TEXT NOT NULL,
    superseded_at TEXT,
    UNIQUE (agent_id, effective_from, to_type)
);

CREATE TABLE IF NOT EXISTS user_accounts (
    owner_id TEXT PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    salt TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    failures INTEGER NOT NULL DEFAULT 0,
    locked_until REAL NOT NULL DEFAULT 0,
    account_role TEXT NOT NULL DEFAULT 'customer' CHECK (account_role IN ('customer', 'staff'))
);

CREATE TABLE IF NOT EXISTS login_sessions (
    token_hash TEXT PRIMARY KEY,
    owner_id TEXT NOT NULL REFERENCES user_accounts(owner_id),
    created_at REAL NOT NULL,
    expires_at REAL NOT NULL,
    revoked_at REAL
);

CREATE INDEX IF NOT EXISTS login_sessions_owner_idx ON login_sessions(owner_id);

CREATE TABLE IF NOT EXISTS sessions (
    session_id TEXT PRIMARY KEY,
    owner_id TEXT NOT NULL,
    thread_id TEXT NOT NULL UNIQUE,
    owner_token_hash TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('active', 'closed')),
    created_at TEXT NOT NULL,
    last_active_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS messages (
    message_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(session_id),
    role TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
    content TEXT NOT NULL,
    created_at TEXT NOT NULL,
    request_id TEXT,
    purpose TEXT NOT NULL DEFAULT 'private',
    metadata_json TEXT NOT NULL DEFAULT '{}',
    sender_type TEXT NOT NULL DEFAULT 'ai' CHECK (sender_type IN ('customer', 'ai', 'staff', 'system')),
    sender_account_id TEXT,
    sender_label TEXT
);

CREATE TABLE IF NOT EXISTS lead_drafts (
    owner_id TEXT PRIMARY KEY,
    last_session_id TEXT NOT NULL REFERENCES sessions(session_id),
    product_id TEXT,
    name TEXT,
    occupation TEXT,
    income_value TEXT,
    income_min TEXT,
    income_max TEXT,
    income_currency TEXT,
    income_period TEXT,
    phone_raw TEXT,
    phone_normalized TEXT,
    status TEXT NOT NULL CHECK (status IN ('unconfirmed', 'confirmed', 'cancelled')),
    draft_json TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS message_request_unique
ON messages(session_id, request_id)
WHERE request_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS handoff_cases (
    case_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES sessions(session_id),
    status TEXT NOT NULL CHECK (status IN ('pending', 'active', 'resolved')),
    trigger_reason TEXT NOT NULL,
    trigger_message_id BIGINT REFERENCES messages(message_id),
    assigned_staff_id TEXT REFERENCES user_accounts(owner_id),
    created_at TEXT NOT NULL,
    accepted_at TEXT,
    resolved_at TEXT,
    resolution_note TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS one_open_handoff_per_session
ON handoff_cases(session_id)
WHERE status IN ('pending', 'active');

CREATE TABLE IF NOT EXISTS leads (
    lead_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id TEXT NOT NULL UNIQUE,
    session_id TEXT NOT NULL REFERENCES sessions(session_id),
    product_id TEXT NOT NULL,
    name TEXT NOT NULL,
    occupation TEXT NOT NULL,
    income_thb NUMERIC(14,2) NOT NULL CHECK (income_thb >= 0),
    income_period TEXT NOT NULL CHECK (income_period = 'monthly_thb'),
    phone_normalized TEXT NOT NULL,
    request_id TEXT NOT NULL UNIQUE,
    payload_hash TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    profile_verified_at TEXT,
    refresh_requested_at TEXT
);

CREATE TABLE IF NOT EXISTS lead_request_log (
    request_id TEXT PRIMARY KEY,
    owner_id TEXT NOT NULL,
    lead_id BIGINT NOT NULL REFERENCES leads(lead_id),
    payload_hash TEXT NOT NULL,
    created_at TEXT NOT NULL
);
